### ISSUE TITLE
0xbrivan - Payable Jobs that require sending NATIVE tokens can not be executed

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-xkeeper-judging#23]
0xbrivan

high

# Payable Jobs that require sending NATIVE tokens can not be executed

## Vulnerability Detail
Relays call [AutomationVault::exec](https://github.com/sherlock-audit/2024-04-xkeeper/blob/b82de26633c1904ccfb3c121497845128f1c5c5f/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L397-L452) to execute jobs allowed to them. A low-level call is made to interact with the target contract and execute the job
```js
(_success,) = _dataToExecute.job.call(_dataToExecute.jobData);
if (!_success) revert AutomationVault_ExecFailed();
```
We can notice here that for payable jobs functions, their execution **will ALWAYS revert**. Notice that even if the contract holds enough native token balance, the transaction will still revert as the value needed by the payable job function is not passed.
## Impact
- Payable functions can not be executed.
## Code Snippet
https://github.com/sherlock-audit/2024-04-xkeeper/blob/b82de26633c1904ccfb3c121497845128f1c5c5f/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L417
## Tool used

Manual Review

## Recommendation
Consider adding a new field in `ExecData` to register the native token amount needed by the job, and pass it when making the call. Below is a suggestion for an updated code.

`IAutomationVault`
```diff
/**
   * @notice The data to execute a job
   * @param job The address of the job
   * @param jobData The data to execute the job
+  * @param nativeTokenAmount the native token amount needed to execute the job
   */
  struct ExecData {
    address job;
    bytes jobData;
+   uint256 nativeTokenAmount 
  }
```
`AutomationVault`
```diff
/// @inheritdoc IAutomationVault
function exec(address _relayCaller, ExecData[] calldata _execData, FeeData[] calldata _feeData) external {
    // rest of the code
-    (_success,) = _dataToExecute.job.call(_dataToExecute.jobData);
+    if (dataToExecute.nativeTokenAmount > 0) {
+    (_success,) = _dataToExecute.job.call{value: _dataToExecute.nativeTokenAmount}(_dataToExecute.jobData);
+    } else {
+     (_success,) = _dataToExecute.job.call(_dataToExecute.jobData);
+    }
    if (!_success) revert AutomationVault_ExecFailed();

    // rest of the code
}
```

**Comment by Brivan-26** [comment]
Where it was stated that the protocol is not intended to work this way? @IllIllI000 @Hash01011122 ?

**Comment by IllIllI000** [comment]
the contract has a receive(), so it's clear the tokens are meant to be sent directly as a payment, not as tokens for a job

**Comment by Brivan-26** [comment]
Escalate

I still can't get why the existence of `receive` means that jobs that require native tokens are not supported.

If the function has the `receive` fallback, it just means that it might receive funds (so the admin can withdraw them by calling `withdrawFunds`) and I do believe also that the `receive` exists so the owner can fund the vault contract so it sends them along to execute payable jobs 

@Hash01011122 You mentioned:
> there is no apparent rationale for a job to necessitate receiving ETH.

This is an unrelated reason at all to invalidate the issue, your argument here is the same as *why anyone would create a payable function*

A job is just a call to another contract, and the owner could choose any function call to automate(especially swaps functions on different AMMs, and DEXs in which some of them are payable.. example: swapping eth for another token).

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I still can't get why the existence of `receive` means that jobs that require native tokens are not supported.
> 
> If the function has the `receive` fallback, it just means that it might receive funds (so the admin can withdraw them by calling `withdrawFunds`) and I do believe also that the `receive` exists so the owner can fund the vault contract so it sends them along to execute payable jobs 
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
