### ISSUE TITLE
cryptic - Malicious keeper disputer can target xKeeper vaults to cause permanent DoS on vault's ability to use Keeper Relays

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-xkeeper-judging#63]
cryptic

medium

# Malicious keeper disputer can target xKeeper vaults to cause permanent DoS on vault's ability to use Keeper Relays

## Summary
The protocol mentioned that only the `Gelato Relay Network` is trusted and other external protocols are restricted. A malicious actor of the `Keeper Network` with `disputer` role, having the intent to cause harm to the xKeeper protocol, can target xKeeper vault owners to cause permanent DoS of the ability for any jobs to be executed on `xKeeper vaults` via the Keeper Network.  

## Vulnerability Detail
`Keep3rRelay::exec` & `Keep3rBondedRelay::exec`
```javascript
    // Inject the final call which will issue the payment to the keeper
    _execDataKeep3r[_execDataLength + 1] = IAutomationVault.ExecData({
      job: address(KEEP3R_V2),
      jobData: abi.encodeWithSelector(IKeep3rV2.worked.selector, msg.sender)
    });
```

Both contracts append this job to the end of the list of jobs to execute, this is to ensure the payment is sent to the keeper. Once the jobs are executed via `AutomationVault::exec`:

```javascript
      (_success,) = _dataToExecute.job.call(_dataToExecute.jobData);
      if (!_success) revert AutomationVault_ExecFailed();
``` 

The last job it will execute is the `worked` function of the keeper network to issue the payment.

`Keep3rJobWorkable.sol` https://etherscan.io/address/0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC#code:~:text=10%20of%2039%20%3A-,Keep3rJobWorkable.sol,-1
```javascript
function worked(address _keeper) external override {
    address _job = msg.sender;
@>  if (disputes[_job]) revert JobDisputed();
    if (!_jobs.contains(_job)) revert JobUnapproved();

    if (_updateJobCreditsIfNeeded(_job)) {
      emit LiquidityCreditsReward(_job, rewardedAt[_job], _jobLiquidityCredits[_job], _jobPeriodCredits[_job]);
    }

    (uint256 _boost, uint256 _oneEthQuote, uint256 _extraGas) = IKeep3rHelper(keep3rHelper).getPaymentParams(bonds[_keeper][keep3rV1]);

    uint256 _gasLeft = _getGasLeft();
    uint256 _payment = _calculatePayment(_gasLeft, _extraGas, _oneEthQuote, _boost);

    if (_payment > _jobLiquidityCredits[_job]) {
      _rewardJobCredits(_job);
      emit LiquidityCreditsReward(_job, rewardedAt[_job], _jobLiquidityCredits[_job], _jobPeriodCredits[_job]);

      _gasLeft = _getGasLeft();
      _payment = _calculatePayment(_gasLeft, _extraGas, _oneEthQuote, _boost);
    }

    _bondedPayment(_job, _keeper, _payment);
    emit KeeperWork(keep3rV1, _job, _keeper, _payment, _gasLeft);
  }
```

A malicious actor with disputer role can cause DoS of this function, by adding the address of the vault to the list `disputes`. 

`Keep3rDisputable.sol` https://etherscan.io/address/0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC#code:~:text=14%20of%2039%20%3A-,Keep3rDisputable.sol,-1
```javascript
  function dispute(address _jobOrKeeper) external override onlyDisputer {
    if (disputes[_jobOrKeeper]) revert AlreadyDisputed();
    disputes[_jobOrKeeper] = true;
    emit Dispute(_jobOrKeeper, msg.sender);
  }
```

When `if (disputes[_job])` is executed, the `worked` function will revert, causing the entire transaction from the call within `Keep3rBondedRelay::exec` or `Keep3rRelay::exec` to revert. The Keeper Network relays integrated will no longer function and will always revert. This can be done to target vaults specifically of the xKeeper network to cause harm to the protocol.

## Impact
xKeeper vault owners will be unable to use Keep3r Network for relays, rendering the `Keep3erRelay.sol` and `Keep3rBondedRelay.sol` contracts useless. In addition to DoS, attempts to add these relays to the vault will be wasted gas fees for vault owners.

## Code Snippet
https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L417

https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/relays/Keep3rBondedRelay.sol#L77-L80

https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/relays/Keep3rRelay.sol#L52-L55

https://etherscan.io/address/0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC#code:~:text=14%20of%2039%20%3A-,Keep3rDisputable.sol,-1

https://etherscan.io/address/0xeb02addCfD8B773A5FFA6B9d1FE99c566f8c44CC#code:~:text=10%20of%2039%20%3A-,Keep3rJobWorkable.sol,-1

## Tool used
Manual Review

## Recommendation
Ensure that the protocol is aware of this situation and plan ahead.

**Comment by crypticdefense** [comment]
@Hash01011122 This issue, along with #64, should be valid per [sherlock rules](https://docs.sherlock.xyz/audits/judging/judging)

![image](https://github.com/sherlock-audit/2024-04-xkeeper-judging/assets/163693920/94f42b7c-d561-49be-aa37-4abcaef9118c)

The protocol explicitly stated in the [contest details](https://audits.sherlock.xyz/contests/248) that only Gelato Relay Network is trusted, and that all other external protocols are restricted. These issues both pertain to admin action (that can harm the xKeeper protocol) via keep3r network which is integrated within the xKeeper protocol.

Furthermore, to give an example, these type of issues were accepted in the recent `Napier Contest`, where the protocol integrated FRAX and explicitly stated in the contest details that it is restricted:

Sources: 
https://github.com/sherlock-audit/2024-01-napier-judging/issues/108
https://github.com/sherlock-audit/2024-01-napier-judging/issues/95

Therefore, this issue and #64 are valid findings.
