### ISSUE TITLE
s1ce - Bytes4 cast in AutomationVault exec allows keeper to send potentially unapproved data

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-xkeeper-judging#77]
s1ce

medium

# Bytes4 cast in AutomationVault exec allows keeper to send potentially unapproved data

## Summary
In AutomationVault exec function, the function selectors for each of the jobs are checked, presumably for added security. However, because of a bytes4 cast, the malicious keeper can send in less than 4 bytes of data, which may trigger a fallback function, while still bypassing the function selector check. 

## Vulnerability Detail

If the malicious keeper sends less than 4 bytes in `_dataToExecute.jobData`, and the 0-padded version of the bytes has been white listed as a selector, then the malicious keeper can potentially call some type of fallback function within the job contract rather than the correct function. This can lead to unfortunate consequences, as this can be gas intensive, and the keeper is paid based on the amount of gas consumed (at least in OpenRelay), which means that the keeper can charge the Autonomous Vault owner more than intended. 

The relevant code snippet is here in exec:

```solidity
            if (
                !_approvedJobSelectors[msg.sender][_dataToExecute.job].contains(
                    bytes4(_dataToExecute.jobData)
                )
            )
```
## Impact
Malicious keepers can call fallback functions that should not be callable

## Code Snippet
https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L414

## Tool used

Manual Review

## Recommendation
Don't use bytes4 cast

Duplicate of #68

**Comment by s1ce** [comment]
Escalate

Not sure why this was excluded. Duplicate of #68

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Not sure why this was excluded. Duplicate of #68

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Hey, I think you are getting it wrong root cause and attack path #68 and this is entirely different. Also this doesn't look duplicate of #60 too, As your issue doesn't highlight any rational impact as in #93 and #60. Do want to add anything @s1ce??

**Comment by s1ce** [comment]
@Hash01011122 The impact is clearly stated in the "Impact" section, which is identical to #68 : `Malicious keepers can call fallback functions that should not be callable`

The attack path is also the exact same, please reread it

**Comment by cvetanovv** [comment]
I somewhat agree with the escalation that it could be duplicated with #68, but #68 would be invalidated, so I'll reject the escalation and leave the issue as is.

**Comment by s1ce** [comment]
@cvetanovv Why should escalation be rejected? From my perspective, this was judged incorrectly, and I was forced to escalate because I didn't know the status of the other issue.

**Comment by cvetanovv** [comment]
@s1ce You're right there, and I'm going to change my mind about the escalation and will duplicate it with #68.

The reason I had is that whether it is duplicated or not, the result will be an invalid issue. Accepted escalation would hurt Lead Judge awards. Even if escalation is rejected and #68 remains valid, we check everything is correct before the results and will change this issue to valid as well. But from your perspective, you're right to accept the escalation. 

I would advise you to write more detailed reports in the future. This is to your advantage and will only increase your chances of getting a reward. Compare this issue with #68 and you will see the differences. Even see just the `Impact` and `Recommendation` sections. In your issue in the `Impact` section, you only say that someone can call fallback functions which in itself is not a problem. The other issue says the same but also explains why this is a problem. This also applies in other places where you catch the roots, although not as well described.

I am planning to accept the escalation and duplicate with #68.

**Comment by ghost** [comment]
I will respect whatever decision @cvetanovv will be making here. But I just want to point out looking at the report of Watson it was a bit ambiguous to make decision whether to consider the issue as valid and consider it as dup of #68, as the report doesn't show any valid attack vector.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #68

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [s1ce](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/77/#issuecomment-2074013745): accepted

**Comment by ghost** [comment]
@Evert0x @cvetanovv, I would like to know why this issue got accepted in the first place?
> #### Rules for Escalation:
>Escalation will not be accepted in case the reward distribution is not affected.

**Comment by ghost** [comment]
I think you should edit the status of escalation from accepted to rejected
