### ISSUE TITLE
s1ce - OpenRelay payment doesn't include L1 Data fees

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-xkeeper-judging#81]
s1ce

high

# OpenRelay payment doesn't include L1 Data fees

## Summary

Keepers will be undercompensated on L2s, such as Optimism or Blast, because the payment calculation does not include L1 Data fees

## Vulnerability Detail

There are two types of gas fees on L2s: The L2 execution fees and the L1 Data fees. The current formula, which multiplies the block base fee times the gas used, only takes into account the execution fees. The L1 Data fees can potentially be costly and are not included as part of this calculation, so keepers could be undercompensated for their transactions as a result. 

The error is in this computation:

```solidity
    uint256 _initialGas = gasleft();
    _automationVault.exec(msg.sender, _execData, new IAutomationVault.FeeData[](0));
    uint256 _gasSpent = _initialGas - gasleft();

    // Calculate the payment for the relayer
    uint256 _payment = (_gasSpent + GAS_BONUS) * block.basefee * GAS_MULTIPLIER / BASE;
```

## Impact

Keepers could be undercompensated

## Code Snippet

https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/relays/OpenRelay.sol#L29

## Tool used

Manual Review

## Recommendation
Account for L1 Data Fee

Duplicate of #57

**Comment by s1ce** [comment]
Escalate

Not sure why this was excluded. Duplicate of #57

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Not sure why this was excluded. Duplicate of #57 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Agreed this is indeed duplicate of #57

**Comment by cvetanovv** [comment]
I agree it is a duplicate of #57.

Planning to accept the escalation and duplicate with #57.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #57

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [s1ce](https://github.com/sherlock-audit/2024-04-xkeeper-judging/issues/81/#issuecomment-2074012867): accepted
