### ISSUE TITLE
MrPotatoMagic - GelatoRelay allows ERC20 token payments contrary to the spec of ETH only, which may lead to freezing of funds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-04-xkeeper-judging#97]
MrPotatoMagic

high

# GelatoRelay allows ERC20 token payments contrary to the spec of ETH only, which may lead to freezing of funds

## Summary

According to the contest README under the question **Please discuss any design choices you made**, the team has mentioned that the Gelato Relay is only set to accept ETH as seen below:
```solidity
Open Relay and Gelato Relay are currently set to only accept ETH due to its easy payment calculation
```

## Vulnerability Detail

This is not true since the [exec()](https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/relays/GelatoRelay.sol#L28) function in the GelatoRelay.sol contract currently allows fee token payments in ERC20 tokens as well as seen on Line 34 [here](https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/relays/GelatoRelay.sol#L34).

## Impact

Due to this, if the receiver cannot handle/withdraw tokens from their contract, those tokens would be lost. Note that the receiver was expecting ETH and had support for it but instead received ERC20 tokens which they might not be able to handle.

The issue also points out the deviation from the intended specification/behaviour defined by the sponsors in the README, which itself is a problem.

## Code Snippet

Here's the execution flow:
 - Line 28 - Approved caller (or anyone in case _ALL is enabled) calls exec() function to execute a selector on a job contract.
 - Line 30 - `_fee` amount and `_feeToken` address are retrieved. 
 - Line 38 - Calls exec() on the automationVault contract, which sends the ERC20 tokens to the recipient as seen [here](https://github.com/sherlock-audit/2024-04-xkeeper/blob/main/xkeeper-core/solidity/contracts/core/AutomationVault.sol#L442).
 - But since the receiver was expecting ETH and not ERC20 tokens, they might not be able handle the tokens due to missing support for them. 
```solidity
File: GelatoRelay.sol
27:   /// @inheritdoc IGelatoRelay
28:   function exec(IAutomationVault _automationVault, IAutomationVault.ExecData[] calldata _execData) external {
29:     // Get the fee details
30:     (uint256 _fee, address _feeToken) = AUTOMATE.getFeeDetails();
31: 
32:     // Create fee data
33:     IAutomationVault.FeeData[] memory _feeData = new IAutomationVault.FeeData[](1);
34:     
35:     _feeData[0] = IAutomationVault.FeeData(FEE_COLLECTOR, _feeToken, _fee);
36: 
37:     // Execute the automation vault
38:     _automationVault.exec(msg.sender, _execData, _feeData);
39: 
40:     // Emit the event
41:     emit AutomationVaultExecuted(_automationVault, msg.sender, _execData, _feeData);
42:   }

```

## Tool used

Manual Review

## Recommendation

Consider checking the _feeToken returned by AUTOMATE.getFeeDetails() is the native token. 

Duplicate of #4

**Comment by mcgrathcoutinho** [comment]
Escalate
Hi @Hash01011122, I believe this issue has been incorrectly duplicated. This points out a deviation from the specification, which may lead to freezing of funds. Note this is not the receiver's error since they were never expecting to receive/handle the ERC20 token but only execute ETH jobs.

**Comment by sherlock-admin2** [comment]
> Escalate
> Hi @Hash01011122, I believe this issue has been incorrectly duplicated. This points out a deviation from the specification, which may lead to freezing of funds. Note this is not the receiver's error since they were never expecting to receive/handle the ERC20 token but only execute ETH jobs.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by mcgrathcoutinho** [comment]
@Hash01011122 Would appreciate a response on this since this has been incorrectly dupped and I believe should be considered a valid issue.

**Comment by mcgrathcoutinho** [comment]
@Hash01011122 and @cvetanovv, this issue has been incorrectly duplicated. Can you please look into this?
